name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      # - name: Ejecutar ESLint
      #   run: npx eslint "**/*.js"

      - name: Verficar instalacion
        run: echo "Infraestructura CI/CD configurada correctamente"